version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres-multiple-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-multiple-dbs-postgres.sh:/docker-entrypoint-initdb.d/init-multiple-dbs-postgres.sh

  config-server:
    build:
      context: ../config-server/config-server
    container_name: config-server
    ports:
      - 8081:8081
    depends_on:
      - postgres
  eureka-service:
    build:
      context: ../eureka-service
    ports:
      - 8761:8761
    depends_on:
      - config-server
    restart: on-failure
  gateway-service:
    build:
      context: ../gateway-service
    ports:
      - 8080:8080
    depends_on:
      - eureka-service
    restart: on-failure
  categoria-service:
    build:
      context: ../categoria-service
    ports:
      - 8082:8082
    depends_on:
      - postgres
      - config-server
      - eureka-service
    restart: on-failure
  producto-service:
    build:
      context: ../microservice-producto
    ports:
      - 8083:8083
    depends_on:
      - postgres
      - config-server
      - eureka-service
    restart: on-failure
  cliente-service:
    build:
      context: ../microservice-cliente
    ports:
      - 8084:8084
    depends_on:
      - postgres
      - config-server
      - eureka-service
    restart: on-failure
  venta-service:
    build:
      context: ../microservice-venta
    ports:
      - 8085:8085
    depends_on:
      - postgres
      - config-server
      - eureka-service
    restart: on-failure
volumes:
  postgres_data:
