version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres-multiple-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-dbs-postgres.sh:/docker-entrypoint-initdb.d/init-multiple-dbs-postgres.sh
volumes:
  postgres_data: